# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and lockfile
COPY package.json package-lock.json ./

# Install dependencies (including dev for source start)
RUN npm install --ignore-scripts

# Copy source
COPY . .

# Expose port for practices (stdio use)
EXPOSE 8080

# Default command (overridden by MCP start)
CMD ["node", "index.js"]
